version: '3.9'
services:
  producer-service:
    build:
      context: ./producer-service
      dockerfile: ./producer.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    environment:
      RABBIT_URL: 'amqp://guest:guest@rabbitmq'

  consumer-service:
    build:
      context: ./consumer-service
      dockerfile: ./consumer.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    environment:
      RABBIT_URL: 'amqp://guest:guest@rabbitmq'

  rabbitmq:
    image: 'rabbitmq:3.12-alpine'
    ports:
      - '5672:5672'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data-rabbitmq/:/var/lib/rabbitmq
